name: mbapp
description: 摩贝百科

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^1.1.0
  flutter_spinkit: ^4.1.2
  url_launcher: ^5.7.2
  flutter_easyrefresh: ^2.1.6
  provider: ^4.3.2
  fluro: ^1.6.3
  shared_preferences: ^0.5.7+3
  curved_navigation_bar: ^0.3.3
  english_words: ^3.1.0
  flutter_webview_plugin: ^0.3.5
  flutter_swiper: 1.1.6
  # https://github.com/PonnamKarthik/FlutterToast
  # https://github.com/flutterchina/dio
  dio: ^3.0.9
  # https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: 1.0.0
  flutter_html: ^0.9.8
  scroll_to_index: ^1.0.6
  connectivity: ^0.4.4
  fluttertoast: ^7.1.1
  json_annotation: ^3.0.1 #json数据生成实体类

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0 #json数据生成实体类
  json_serializable: ^3.3.0 #json数据生成实体类

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/loading.jpeg
    - assets/images/company.jpg
    - assets/images/login_button.png
    

  #主搜索页
    - assets/images/home/home_bg.png
    - assets/images/home/icon_default.png
    - assets/images/home/icon_search.png
    - assets/images/home/iv_search.png
    - assets/images/home/btn_search.png
    - assets/images/home/icon_hotsearch.png

  #个人中心 
    - assets/images/personal/mine_mark_icon.png
    - assets/images/personal/mine_opinion_icon.png
    - assets/images/personal/mine_service_icon.png
    - assets/images/personal/mine_clean_cache_icon.png


  #轮播图片
    - assets/images/banners/1.jpeg
    - assets/images/banners/2.jpeg
    - assets/images/banners/3.jpeg
    - assets/images/banners/4.jpeg

  #产品图片
    - assets/images/products/1.jpeg
    - assets/images/products/2.jpeg
    - assets/images/products/3.jpeg
    - assets/images/products/4.jpeg

  #百科图片
    - assets/images/baike/icon_table.png
    - assets/images/baike/icon_follow_bg.png
    - assets/images/baike/icon_cancel.png
    - assets/images/baike/icon_home.png
    - assets/images/baike/icon_share.png
    - assets/images/baike/icon_basic.png
    - assets/images/baike/icon_properties.png
    - assets/images/baike/icon_safe.png
    - assets/images/baike/icon_use.png
    - assets/images/baike/icon_msds.png
    - assets/images/baike/icon_spectrum.png
    - assets/images/baike/icon_analysis.png
    - assets/images/baike/icon_synthesis.png
    - assets/images/baike/icon_import.png
    - assets/images/baike/icon_precursor.png
    - assets/images/baike/icon_downstream.png
    - assets/images/baike/icon_toxicity.png
    - assets/images/baike/icon_route.png
    - assets/images/baike/icon_routeadd.png
    - assets/images/baike/icon_collect.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
